# eks-node-demo.yaml

apiVersion: v1
kind: Namespace
metadata:
  name: node-demo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-demo
  namespace: node-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-demo-deployment
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: node-demo-deployment
    spec:
      containers:
        - image: 700478352903.dkr.ecr.eu-central-1.amazonaws.com/trn-node-demo-docker:latest
          name: trn-node-demo-docker
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: node-demo
          resources:
            requests:
              cpu: "0.25"
              memory: "64Mi"
            limits:
              cpu: "1"
              memory: "2Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: node-demo-clusterip
  namespace: node-demo
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 3000
  selector:
    app: node-demo-deployment